site_name: Dokumentation
site_description: Verifleet Dokumentation
site_url: https://verifleet.github.io/vf-documentation/
theme:
  name: material
  font:
    text: Roboto
  logo: assets/vf-logo.svg
  favicon: assets/vf-logo.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

#extra:
#  alternate:
#    - name: Deutsch
#      link: /de/
#      lang: de
#    - name: Français
#      link: /fr/
#      lang: fr
#    - name: English
#      link: /en/
#      lang: en

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

