site_name: Dokumentation
site_description: Dokumentation
# site_url: https://verifleet.github.io/vf-documentation/
theme:
  name: material
  font:
    text: Roboto
  logo: assets/fleethub-logo.svg # wird vom github workflow überschrieben
  # favicon: assets/FleetHub_Logo.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    # - navigation.sections
    # - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

#extra:
#  alternate:
#    - name: Deutsch
#      link: /de/
#      lang: de
#    - name: Français
#      link: /fr/
#      lang: fr
#    - name: English
#      link: /en/
#      lang: en

nav:
  - Home: index.md
  - Einstieg:
    - Erste Schritte: GettingStarted/getting-started.md
    - Kartenführerscheine: GettingStarted/driver-license-card.md
    - Alte Führerscheine: GettingStarted/driver-license-old.md
  - Firmen: 
    - Überblick: Companies/company-management.md
    - Firma anlegen: Companies/company-create.md
    - Firma bearbeiten: Companies/company-edit.md
    - Firma aktivieren/sperren: Companies/company-activate.md
    - Carano-Import: Companies/company-carano-connection.md
  - Benutzer:
    - Überblick: Users/user-management.md
    - Benutzerliste: Users/user-list.md
    - Benutzer anlegen: Users/user-create.md
    - Benutzer bearbeiten: Users/user-edit.md
    - Excel-Import: Users/user-excel-import.md
    - Benutzer-Export: Users/user-export.md
  - Nachkontrollen:
    - Liste der Nachkontrollen: Checks/FollowUpCheckList.md
    - Nachkontrolle: Checks/FollowUpCheck.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - glightbox
  - search