name: dokus
# Nur ein Kommentar
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [verifleet, fleethub, bamaka] # Definiere deine Ziel-Konfigurationen

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-glightbox

      - name: Configure MkDocs for ${{ matrix.target }}
        run: |
          TARGET_NAME="${{ matrix.target }}"
          COLOR=""
          LOGO=""

          case "$TARGET_NAME" in
            "verifleet")
              COLOR="#ff0000"
              LOGO="verifleet-logo.svg"
              ;;
            "fleethub")
              COLOR="#189EDA"
              LOGO="fleethub-logo.svg"
              ;;
            "bamaka")
              COLOR="#ff0000"
              LOGO="bamaka-logo.svg"
              ;;
            *)
              echo "Ungültiges Ziel: $TARGET_NAME"
              exit 1
              ;;
          esac

          echo "::group::Updating mkdocs.yml for ${{ matrix.target }}"
          sed -i "s|site_name: .*|site_name: ${{ matrix.target }}|" mkdocs.yml
          sed -i "s|theme:.*|theme:\n  name: material\n  palette:\n    primary: primary\n    accent: $COLOR|" mkdocs.yml
          sed -i "s|logo: .*|logo: assets/$LOGO|" mkdocs.yml
          echo "::endgroup::"

      - name: Build and Deploy ${{ matrix.target }}
        run: |
          TARGET_NAME="${{ matrix.target }}"
          OUTPUT_DIR="site-$TARGET_NAME"
          mkdocs build -d "$OUTPUT_DIR"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add "$OUTPUT_DIR"
          git commit -m "Deploy $TARGET_NAME" || echo "Keine Änderungen zum Übertragen."
          git push origin HEAD:refs/heads/gh-pages-"$TARGET_NAME" --force