#!/usr/bin/env bash

set -e

TARGET_NAME="${TARGET_NAME:-verifleet}"

case "$TARGET_NAME" in
  "verifleet")
    COLOR="#ff0000"
    LOGO="verifleet-logo.svg"
    ;;
  "fleethub")
    COLOR="#189EDA"
    LOGO="fleethub-logo.svg"
    ;;
  "bamaka")
    COLOR="#ff0000"
    LOGO="bamaka-logo.svg"
    ;;
  *)
    echo "Ungültiges Ziel: $TARGET_NAME"
    exit 1
    ;;
esac

echo "::group::Updating mkdocs.yml for $TARGET_NAME"

# Setze site_name
sed -i "s/^site_name:.*/site_name: $TARGET_NAME/" mkdocs.yml

# Ersetze theme block vollständig mit printf
THEME_BLOCK=$(cat <<EOF
theme:
  name: material
  palette:
    primary: primary
    accent: $COLOR
EOF
)

# Entferne alte theme-Zeile(n)
awk '
  BEGIN { skip=0 }
  /^theme:/ { print "'$THEME_BLOCK'"; skip=1; next }
  skip && /^[^[:space:]]/ { skip=0 }
  !skip
' mkdocs.yml > mkdocs.tmp && mv mkdocs.tmp mkdocs.yml

# Setze logo
sed -i "s#^logo:.*#logo: assets/$LOGO#" mkdocs.yml

echo "::endgroup::"
