name: Dokus
# Kommentar
on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [verifleet, fleethub, bamaka]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-glightbox

      - name: Configure and Build for ${{ matrix.target }}
        run: |
          TARGET_NAME="${{ matrix.target }}"
          COLOR=""
          LOGO=""

          case "$TARGET_NAME" in
            "verifleet")
              COLOR="#ff0000"
              LOGO="verifleet-logo.svg"
              ;;
            "fleethub")
              COLOR="#189EDA"
              LOGO="fleethub-logo.svg"
              ;;
            "bamaka")
              COLOR="#ff0000"
              LOGO="bamaka-logo.svg"
              ;;
            *)
              echo "Ungültiges Ziel: $TARGET_NAME"
              exit 1
              ;;
          esac

          cp mkdocs.yml mkdocs.temp.yml
          sed -i "s|site_name: .*|site_name: $TARGET_NAME|" mkdocs.temp.yml
          sed -i "s|logo: .*|logo: assets/$LOGO|" mkdocs.temp.yml
          sed -i "/theme:/,/^$/c\theme:\n  name: material\n  palette:\n    primary: custom\n    accent: $COLOR" mkdocs.temp.yml

          mkdocs build -f mkdocs.temp.yml -d site/${TARGET_NAME}

      - name: Upload ${{ matrix.target }} site folder
        uses: actions/upload-artifact@v4
        with:
          name: site-${{ matrix.target }}
          path: site/${{ matrix.target }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: site

      - name: Flatten site structure
        run: |
          mkdir merged_site
          for dir in site/*; do
            if [ -d "$dir" ]; then
              NAME=$(basename "$dir")
              mv "$dir" "merged_site/$NAME"
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./merged_site
          publish_branch: gh-pages
